### ISSUE TITLE
Training Problems

### ISSUE THREAD

**Issue by Callifrey** [minhmanho/semantic-driven_colorization#2]
Sorry to interrupt again. When I reproduce the training procedure, the model seem to suffer from overfitting. I have tried more aggressive data augmentation(eg: larger random crop), it still don't work for this. And I also tried add different regularizaiton constraint, but it seem hard to converge to a good result. That's a difficult trade-off. I woder whether you have met this problem during your training steps. If so, I will appreciate your helpful experiment suggestions. Thanks a lot!
Best!

**Comment by minhmanho** [comment]
Hi,

I didn't try further data augmentation and regularization.
Could you please share your training code with manminhho.cs@gmail.com?
I will take a look.
In the meantime, I will prepare the training code for you.

Best,
Man
